//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>
#include <Display.h>


//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR Content goes here. Remember to clear flag bits:
// TCON::TF0 (Timer 0 Overflow Flag)
//
//-----------------------------------------------------------------------------
extern volatile uint8_t digit_array[4];
extern volatile bool g_digits_ready;
SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
{
  static uint16_t timer_0_counter = 0U;
  static uint8_t current_digit;
  static uint8_t idx = 2;

  TCON_TF0 = 0;

  timer_0_counter++;

  if(timer_0_counter == 5 && g_digits_ready == true)
  {
      current_digit = digit_array[idx];
      select_display(idx);
      send_to_shift_register(current_digit);
      idx++;
      if(idx > 3)
      {
          idx = 2;
          g_digits_ready = false;
      }
      timer_0_counter = 0;
  }
}

